### ISSUE TITLE
Failed to activate the minimap-bookmarks package

### ISSUE THREAD

**Issue by Pysis868** [atom-minimap/minimap-bookmarks#140]
Error: Cannot find module 'atom-package-deps'
Require stack:
- ...\minimap-bookmarks\lib\minimap-bookmarks.js
- C:\Users\<username>\AppData\Local\atom\app-1.60.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (C:\Users\<username>\AppData\Local\atom\app-1.60.0\resources\app\static\<embedded>:11:157942)
    at Module.require (file:///C:/Users/<username>/AppData/Local/atom/app-1.60.0/resources/app.asar/static/index.js:61:43)
    at require (C:\Users\<username>\AppData\Local\atom\app-1.60.0\resources\app\static\<embedded>:11:149229)
    at Object.activate (...\minimap-bookmarks\lib\minimap-bookmarks.js:19:3)
    at Package.activateNow (C:\Users\<username>\AppData\Local\atom\app-1.60.0\resources\app\static\<embedded>:11:3531596)
    at C:\Users\<username>\AppData\Local\atom\app-1.60.0\resources\app\static\<embedded>:14:2607
    at Function.simpleDispatch (C:\Users\<username>\AppData\Local\atom\app-1.60.0\resources\app\static\<embedded>:11:1187666)
    at Emitter.emit (C:\Users\<username>\AppData\Local\atom\app-1.60.0\resources\app\static\<embedded>:11:1189107)
    at PackageManager.triggerDeferredActivationHooks (C:\Users\<username>\AppData\Local\atom\app-1.60.0\resources\app\static\<embedded>:11:386501)
    at C:\Users\<username>\AppData\Local\atom\app-1.60.0\resources\app\static\<embedded>:11:385252

Atom 1.60

**Comment by UziTech** [comment]
Atom has [sunset](https://github.blog/2022-06-08-sunsetting-atom/) and is no longer supported. I am in the process of moving things to [Pulsar Edit](https://pulsar-edit.dev/) but there is still a lot of work to do so I wouldn't expect it any time soon.
